Repository akamai/terraform-provider-akamai, pull requests merged in 2019-08, with the labels that each got.

#27 [AT-DNSFIX]
  akamai/resource_akamai_dns_record.go
Labels: size/XS

#29 Make zone type case insensitive
  akamai/resource_akamai_dns_zone.go
  akamai/resource_akamai_dns_zone_test.go
Labels: size/XS

#38 website: Fix broken link & add check to Travis
  .travis.yml
  GNUmakefile
  website/akamai.erb
Labels: documentation, size/XS

#35 Fix so resourcePropertyActivationUpdate doesn't try to get the property using activationId
  akamai/resource_akamai_property_activation.go
Labels: size/XS

#40 Fixup CPCode and SiteShield behaviors, with unit tests
  akamai/resource_akamai_property.go
  akamai/resource_akamai_property_rules_test.go
Labels: size/M

#42 Fix up support for is_secure attribute
  akamai/resource_akamai_property.go
  akamai/resource_akamai_property_rules.go
  akamai/resource_akamai_property_rules_test.go
  akamai/resource_akamai_property_test.go
Labels: size/XL

#47 Change `akamai_property_rules` to a data source, resource `akamai_property_rules` will now error
  akamai/data_akamai_property_rules.go
  akamai/data_akamai_property_rules_test.go
  akamai/provider.go
  akamai/resource_akamai_property.go
  akamai/resource_akamai_property_rules.go
  akamai/resource_akamai_property_rules_test.go
  examples/data_akamai_property_rules/data_akamai_property_rules.tf
Labels: size/XXL

#46 Ensure provider config works exactly as expected. Lots of tests added.
  akamai/provider.go
  akamai/provider_test.go
  go.mod
Labels: size/XL

#45 Make sure that it activates the latest version when version is unset
  akamai/resource_akamai_property_activation.go
  akamai/resource_akamai_property_activation_test.go
Labels: size/L

#48 Ensure travis doesn't build twice for branches that are also PRs
  .travis.yml
Labels: size/XS

#34 fixMXsort
  akamai/resource_akamai_dns_record.go
Labels: size/XS

#49 <priority> <weight> <port> <target>
  akamai/resource_akamai_dns_record.go
Labels: size/XS

#50 docs/appendix: Fix broken link to akamai_edge_hostname resource
  website/docs/g/appendix.html.markdown
Labels: documentation, size/XS
