Repository akamai/terraform-provider-akamai, pull requests merged in 2019-07, with the labels that each got.

#13 Add and refactor schema validation
  .travis.yml
  GNUmakefile
  akamai/resource_akamai_dns_record.go
  akamai/resource_akamai_dns_record_test.go
  akamai/resource_akamai_dns_zone.go
  akamai/resource_akamai_dns_zone_test.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go
  vendor/github.com/hashicorp/terraform/helper/validation/validation.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#15 Don't fixup valid CPCode schemas
  akamai/resource_akamai_property.go
Labels: bug, size/XS

#16 Add `property` and `dns` config blocks to allow easier setting of credentials
  akamai/provider.go
Labels: enhancement, size/L

#17 Don't deactivate unintentionally
  akamai/resource_akamai_property_activation.go
Labels: bug, size/XS

#14 Split apart properties and edge hostnames completely, removing any magic around hostname <-> edge hostname links.
  akamai/resource_akamai_edge_hostname.go
  akamai/resource_akamai_property.go
  examples/akamai_property/property-json/merge.sh
  examples/akamai_property/property-json/property.tf
  examples/akamai_property/property-json/rules.json
Labels: bug, size/XXL

#20 AT-17 Fix SRV DNS parameter order
  akamai/resource_akamai_dns_record.go
Labels: size/XS

#21 IPv4 typo, don't try to deactivate a non-active version
  akamai/resource_akamai_edge_hostname.go
  akamai/resource_akamai_property_activation.go
Labels: size/M
