Repository akamai/terraform-provider-akamai, pull requests merged in 2020-02, with the labels that each got.

#97 Doc and Example Updates
  examples/community-examples/README.md
  examples/onboard-Ion/README.md
  examples/onboard-Ion/akamai.tf
  examples/onboard-Ion/rules/rules.json
  examples/onboard-Ion/rules/snippets/CORS response.json
  examples/onboard-Ion/rules/snippets/LocationControl
  examples/onboard-Ion/rules/snippets/Offload.json
  examples/onboard-Ion/rules/snippets/Origin_CommonSettings.json
  examples/onboard-Ion/rules/snippets/PathBasedNoStore.json
  examples/onboard-Ion/rules/snippets/PathBasedTTL.json
  examples/onboard-Ion/rules/snippets/Performance.json
  examples/onboard-Ion/rules/snippets/RegionalControl.json
  examples/onboard-Ion/rules/snippets/Timeout.json
  examples/onboard-Ion/rules/snippets/VanityRedirect.json
  examples/onboard-Ion/rules/snippets/apigateway.json
  examples/onboard-Ion/rules/snippets/content_prefresh.json
  examples/onboard-Ion/rules/snippets/contenttargeting_edgescape.json
  examples/onboard-Ion/rules/snippets/datastream.json
  examples/onboard-Ion/rules/snippets/edgeworker.json
  examples/onboard-Ion/rules/snippets/enable_http2.json
  examples/onboard-Ion/rules/snippets/esi.json
  examples/onboard-Ion/rules/snippets/hostname_redirect.json
  examples/onboard-Ion/rules/snippets/imagemanager.json
  examples/onboard-Ion/rules/snippets/mPulse.json
  examples/onboard-Ion/variables.tf
  website/docs/g/appendix.html.markdown
  website/docs/g/faq.html.markdown
  website/docs/r/cp_code.html.markdown
Labels: documentation, size/XXL

#98 docupdate test
  website/docs/g/appendix.html.markdown
  website/docs/g/faq.html.markdown
  website/docs/r/cp_code.html.markdown
Labels: documentation, size/M

#100 Ian contrib examples
  examples/community-examples/property/README.md
  examples/community-examples/property/environments-test/README.md
  examples/community-examples/property/environments-test/environments/dev/main.tf
  examples/community-examples/property/environments-test/environments/preprod/main.tf
  examples/community-examples/property/environments-test/environments/prod/main.tf
  examples/community-examples/property/environments-test/modules/property/main.tf
  examples/community-examples/property/environments-test/modules/property/rules.json
  examples/community-examples/property/environments-test/modules/property/variables.tf
  examples/community-examples/property/foreach-test/README.md
  examples/community-examples/property/foreach-test/main.tf
  examples/community-examples/property/foreach-test/rules/rules.json
  examples/community-examples/property/foreach-test/rules/snippets/authenticate.json
  examples/community-examples/property/foreach-test/rules/snippets/compression.json
  examples/community-examples/property/foreach-test/rules/snippets/default.json
  examples/community-examples/property/foreach-test/rules/snippets/dynamic.json
  examples/community-examples/property/foreach-test/rules/snippets/performance.json
  examples/community-examples/property/foreach-test/rules/snippets/redirect.json
  examples/community-examples/property/foreach-test/rules/snippets/static.json
  examples/community-examples/property/foreach-test/rules/snippets/variables.json
  examples/community-examples/property/foreach-test/variables.tf
  examples/community-examples/property/snippets-test/README.md
  examples/community-examples/property/snippets-test/main.tf
  examples/community-examples/property/snippets-test/rules/rules.json
  examples/community-examples/property/snippets-test/rules/snippets/compression.json
  examples/community-examples/property/snippets-test/rules/snippets/default.json
  examples/community-examples/property/snippets-test/rules/snippets/dynamic.json
  examples/community-examples/property/snippets-test/rules/snippets/performance.json
  examples/community-examples/property/snippets-test/rules/snippets/redirect.json
  examples/community-examples/property/snippets-test/rules/snippets/static.json
  examples/community-examples/property/snippets-test/variables.tf
Labels: size/XXL

#91 [AT-30][Change] Fix optional rule elements
  CHANGELOG.md
  akamai/diff_suppress_funcs.go
  akamai/resource_akamai_property.go
  akamai/resource_akamai_property_activation.go
  akamai/resource_akamai_property_activation_test.go
  akamai/resource_akamai_property_test.go
  akamai/util.go
Labels: size/XL

#108 GTM Resource Cleanup
  akamai/data_akamai_gtm_default_datacenter.go
  akamai/provider.go
  akamai/resource_akamai_dns_record.go
  akamai/resource_akamai_gtm_asmap.go
  akamai/resource_akamai_gtm_asmap_test.go
  akamai/resource_akamai_gtm_cidrmap.go
  akamai/resource_akamai_gtm_cidrmap_test.go
  akamai/resource_akamai_gtm_datacenter.go
  akamai/resource_akamai_gtm_datacenter_test.go
  akamai/resource_akamai_gtm_geomap.go
  akamai/resource_akamai_gtm_geomap_test.go
  akamai/resource_akamai_gtm_property.go
  akamai/resource_akamai_gtm_property_test.go
  akamai/resource_akamai_gtm_resource_test.go
  examples/akamai_gtm_domain/full_domain/gtmv1_4.tf
  go.mod
  website/akamai.erb
  website/docs/d/gtm_default_datacenter.html.markdown
  website/docs/g/faq.html.markdown
  website/docs/index.html.markdown
  website/docs/r/gtm_datacenter.html.markdown
  website/docs/r/gtm_property.html.markdown
Labels: documentation, size/XL

#107 [AT-31][Change] Prep release Add changes for gtm cleanup of gock library
  CHANGELOG.md
  akamai/resource_akamai_gtm_asmap_test.go
  akamai/resource_akamai_gtm_cidrmap_test.go
  akamai/resource_akamai_property_activation_test.go
  go.mod
  go.sum
  website/akamai.erb
Labels: documentation, size/XL

#111 [AT-32][Change] Add datasource and Test for property
  akamai/data_akamai_property.go
  akamai/data_akamai_property_test.go
  akamai/provider.go
Labels: size/M
