Repository akamai/terraform-provider-akamai, pull requests merged in 2020-01, with the labels that each got.

#79 [AT-25][Change] Add additional sort to record MX type for consistent SHA results
  akamai/resource_akamai_dns_record.go
Labels: size/S

#86 [AT-29-fix][Change] Rules library swap constants
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/rules.go
Labels: dependencies, size/XS

#90 Bug/origin values customhostheader
  akamai/resource_akamai_property.go
  go.sum
Labels: size/XS
