Repository akamai/terraform-provider-akamai, pull requests merged in 2020-07, with the labels that each got.

#167 Gb -165
  CHANGELOG.md
  akamai/resource_akamai_dns_record.go
Labels: size/XS

#94 fix getting akamai_group
  akamai/data_property_akamai_group.go
Labels: dependencies, size/XS

#162 [AT-40][Add] Preliminary Logging CorrelationID
  CHANGELOG.md
  akamai/data_akamai_cp_code.go
  akamai/data_akamai_property.go
  akamai/data_property_akamai_contract.go
  akamai/data_property_akamai_group.go
  akamai/diff_suppress_funcs.go
  akamai/provider.go
  akamai/resource_akamai_cp_code.go
  akamai/resource_akamai_edge_hostname.go
  akamai/resource_akamai_edge_hostname_test.go
  akamai/resource_akamai_property.go
  akamai/resource_akamai_property_activation.go
  akamai/resource_akamai_property_activation_test.go
  akamai/resource_akamai_property_test.go
  akamai/resource_akamai_property_variables.go
  akamai/util.go
  go.mod
  go.sum
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/edgegrid/log.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/edgegrid/signer.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/contracts.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/cpcodes.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/edgehostnames.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/groups.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/hostnames.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/products.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/properties.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/ruleformats.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/rules.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/search.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/service.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/versions.go
  vendor/modules.txt
Labels: dependencies, size/XL

#169 fix for GH-146
  website/docs/r/property_variables.html.markdown
Labels: documentation, size/XS

#170 [AT-41][Change] Fixed default group use case
  akamai/data_property_akamai_group.go
  akamai/resource_akamai_property_activation.go
Labels: size/S

#177 Release of AT-41
  CHANGELOG.md
Labels: size/XS
