Repository akamai/terraform-provider-akamai, pull requests merged in 2020-05, with the labels that each got.

#144 Stable website
  GNUmakefile
  website/docs/index.html.markdown
Labels: documentation, size/XS

#149 Finalize DNSv2 UpdateRelease
  CHANGELOG.md
  GNUmakefile
  akamai/provider.go
  akamai/resource_akamai_dns_record.go
  akamai/resource_akamai_gtm_property_test.go
  examples/akamai_dns_zone/add-records/dnsv2.tf
  examples/akamai_dns_zone/add-zone-records/dnsv2.tf
  examples/akamai_dns_zone/add-zone/dnsv2.tf
  go.mod
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v2/errors.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v2/record.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v2/record_lookup.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v2/zone.go
  website/docs/g/get_started_dns_zone.html.markdown
  website/docs/g/get_started_gtm_domain.html.markdown
  website/docs/g/get_started_property.html.markdown
  website/docs/r/dns_record.html.markdown
  website/docs/r/dns_zone.html.markdown
Labels: dependencies, documentation, size/XXL

#153 Fix Bugs in Zone Create and Exists
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/client-v1/client.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v2/authorities.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/activations.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/available.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/client_settings.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/contracts.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/cpcodes.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/custombehaviors.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/customoverrides.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/edgehostnames.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/groups.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/hostnames.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/init.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/products.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/properties.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/ruleformats.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/rules.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/search.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/versions.go
Labels: dependencies, size/L

#156 Fix MX, SOA record issues
  CHANGELOG.md
  akamai/resource_akamai_dns_record.go
  go.mod
  website/docs/g/get_started_dns_zone.html.markdown
Labels: documentation, size/S
