Repository akamai/terraform-provider-akamai, pull requests merged in 2020-03, with the labels that each got.

#113 [AT-35][Change] Add support for cache lib from edge lib v0.9.9
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/.DS_Store
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/go.mod
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/go.sum
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/contracts.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/cpcodes.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/groups.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/service.go
  vendor/github.com/patrickmn/go-cache/CONTRIBUTORS
  vendor/github.com/patrickmn/go-cache/LICENSE
  vendor/github.com/patrickmn/go-cache/README.md
  vendor/github.com/patrickmn/go-cache/cache.go
  vendor/github.com/patrickmn/go-cache/cache_test.go
  vendor/github.com/patrickmn/go-cache/sharded.go
  vendor/github.com/patrickmn/go-cache/sharded_test.go
Labels: dependencies, size/XXL

#106 add workspaces-test community example
  examples/community-examples/property/workspaces-test/.gitignore
  examples/community-examples/property/workspaces-test/README.md
  examples/community-examples/property/workspaces-test/main.tf
  examples/community-examples/property/workspaces-test/rules/rules.tfjson
  examples/community-examples/property/workspaces-test/rules/snippets/cors.tfjson
  examples/community-examples/property/workspaces-test/rules/snippets/default.tfjson
  examples/community-examples/property/workspaces-test/stages/stage.tfvars.dist
  examples/community-examples/property/workspaces-test/terraform.tfvars.dist
Labels: size/XL

#114 [AT-36][Change] Add v0.9.9 edge library
  CHANGELOG.md
  akamai/util.go
  go.mod
  go.sum
Labels: size/XS

#117 GTM waitForCompletion fix
  akamai/resource_akamai_gtm_domain.go
Labels: size/XS

#118 [AT-37][Change] Add support for cache for edgehostnames and products
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/edgehostnames.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/papi-v1/products.go
Labels: dependencies, size/M

#119 GTM-FIX workaround for tests
  akamai/resource_akamai_gtm_property_test.go
Labels: size/XS

#120 Stable website
  website/akamai.erb
Labels: documentation, size/XS

#122 fix akamai_property resource cp_name attr docs
  website/docs/r/property.html.markdown
Labels: documentation, size/XS

#123 Akamaicdn
  akamai/resource_akamai_dns_record.go
Labels: size/XS
